In [1]:
import pandas as pd

In [22]:
df = pd.read_csv('day.csv', encoding = 'utf-8')

In [23]:
df

,'대여일자','대여소번호','대여소','대여구분코드','SEX_CD','연령대코드','이용건수','운동량','탄소량','이동거리(M)','이동시간(분)'
0,'2018-06-01','733',' 신정이펜하우스314동','정기','F','~10대',3,290.72,2.66,11490,93
1,'2018-06-01','736',' 오솔길공원','정기','F','~10대',2,50.54,0.61,2600,18
2,'2018-06-01','746',' 목동2단지 상가','정기','F','~10대',1,53.02,0.48,2060,51
3,'2018-06-01','945',' 기자촌 사거리','정기','F','~10대',1,54.33,0.65,2800,17
4,'2018-06-01','508',' 성수아카데미타워 앞','정기','F','~10대',1,46.81,0.46,1970,11
5,'2018-06-01','1041',' 묘곡초등학교','정기','F','~10대',2,111.69,1.13,4900,23
6,'2018-06-01','1044',' 굽은다리역','정기','F','~10대',1,33.98,0.33,1430,7
7,'2018-06-01','1152',' 마곡역교차로','정기','F','~10대',1,12.67,0.15,640,3
8,'2018-06-01','1153',' 발산역 2번출구','정기','F','~10대',3,67.09,0.69,2990,23
9,'2018-06-01','1157',' 강서구청','정기','F','~10대',1,39.12,0.35,1520,12
10,'2018-06-01','1251',' 석촌역 2번출구','정기','F','~10대',1,53.66,0.63,2710,18
11,'2018-06-01','1262',' 송파여성문화회관 앞','정기','F','~10대',1,33.66,0.39,1700,12
12,'2018-06-01','1265',' 문정동 근린공원','정기','F','~10대',2,222.19,2.24,9650,59
13,'2018-06-01','1442',' (구)신한은행 중랑교지점','정기','F','~10대',1,111.20,1.00,4320,27
14,'2018-06-01','1526',' 수유동 채선당앞','정기','F','~10대',1,9.78,0.09,380,3
15,'2018-06-01','1530',' 광산사거리','정기','F','~10대',2,21.88,0.19,850,6
16,'2018-06-01','1533',"' 번동 주공3, 4단지 교차로'",'정기','F','~10대',1,34.59,0.42,1820,11
17,'2018-06-01','1643',' 태릉입구역 8번출구','정기','F','~10대',1,49.74,0.36,1570,11
18,'2018-06-01','1653',' 노원역1번출구','정기','F','~10대',1,24.00,0.23,1010,6
19,'2018-06-01','1715',' 서울특별시교육청도봉도서관','정기','F','~10대',1,33.77,0.38,1640,7
20,'2018-06-01','1720',' 도봉구청 옆(중랑천변)','정기','F','~10대',1,259.46,2.17,9360,60
21,'2018-06-01','300',' 정동사거리','정기','F','~10대',1,0.00,0.00,0,0
22,'2018-06-01','2362',' 신사동 가로수길 입구','정기','F','~10대',1,42.21,0.38,1640,9
23,'2018-06-01','2373',' 개포동역 사거리','정기','F','~10대',1,44.79,0.40,1740,12
24,'2018-06-01','3511',' 응봉역 1번출구','정기','F','~10대',1,257.40,2.32,10000,59
25,'2018-06-01','3513',' 상왕십리역 1번출구','정기','F','~10대',1,28.57,0.26,1110,4
26,'2018-06-01','115',' 사루비아 빌딩 앞','정기','F','~10대',1,39.35,0.48,2070,35
27,'2018-06-01','1337',' 돈암성당 옆','정기','F','~10대',2,114.35,1.28,5500,51
28,'2018-06-01','1338',' 용문2교 옆','정기','F','~10대',1,257.40,2.32,10000,82
29,'2018-06-01','1342',' 성북쉼터 앞','정기','F','~10대',1,36.83,0.36,1550,7
...,...,...,...,...,...,...,...,...,...,...,...
378575,'2018-06-30','1122',' 황금내근린공원','단체','M','20대',2,515.21,3.87,16680,97
378576,'2018-06-30','1413',' 봉화산역 5번출구 뒤','단체','M','20대',1,87.77,0.93,4030,22
378577,'2018-06-30','1911',' 구로디지털단지역 앞','단체','M','20대',2,242.22,2.19,9410,82
378578,'2018-06-30','2027',' 중앙대학교 정문','단체','M','20대',5,3242.05,18.99,81870,861
378579,'2018-06-30','2102',' 봉림교 교통섬','단체','M','20대',4,153.09,1.43,6120,32
378580,'2018-06-30','2107',' 도림천 신화교','단체','M','20대',2,76.36,0.72,3110,19
378581,'2018-06-30','1203',' 밀리아나2빌딩 앞','단체','M','20대',2,183.79,1.27,5460,28
378582,'2018-06-30','2247','섬들근린공원','단체','M','20대',3,343.04,2.61,11250,57
378583,'2018-06-30','2307',' 압구정 한양 3차 아파트','단체','M','20대',5,621.93,4.86,20940,147
378584,'2018-06-30','1430',' 중랑구청','단체','M','20대',5,201.69,2.14,9260,65
378585,'2018-06-30','2136',' 신림역 8번출구','단체','M','20대',2,454.94,3.46,14920,109
378586,'2018-06-30','3504',' 원일교회','단체','M','20대',2,84.20,0.87,3730,55
378587,'2018-06-30','1251',' 석촌역 2번출구','단체','M','30대',2,135.42,0.96,4120,87
378588,'2018-06-30','311',' 서울광장 옆','단체','M','30대',2,233.96,1.96,8440,110
378589,'2018-06-30','914',' 새절역 2번출구','단체','M','30대',2,442.31,2.91,12550,173
378590,'2018-06-30','2009',' 보라매역 8번출구','단체','M','30대',2,113.30,0.94,4030,25
378591,'2018-06-30','2285',' LH서초3단지 301동 맞은편','단체','M','40대',3,521.53,5.09,21950,148
378592,'2018-06-30','3519',' 용답역 1번 출구','단체','M','40대',1,34.67,0.24,1030,7
378593,'2018-06-30','116',' 일진아이윌아파트 옆','단체','M','40대',2,188.18,1.22,5280,58
378594,'2018-06-30','1278',' 송파구청 교차로','단체','M','40대',2,355.41,4.16,17950,116
378595,'2018-06-30','1286',' 위례중앙푸르지오 1단지 앞','단체','M','40대',2,485.37,3.89,16790,109
378596,'2018-06-30','170',' 가재울 뉴타운 주유소 옆','단체','M','40대',2,329.21,2.97,12790,95
378597,'2018-06-30','703',' 오목교역 7번출구 앞','단체','M','40대',2,1360.73,17.72,76360,454
378598,'2018-06-30','583',' 청계천 생태교실 앞','단체','M','40대',1,63.95,0.44,1900,10
378599,'2018-06-30','202',' 국민일보 앞','단체','M','40대',4,64.97,2.93,12620,145
378600,'2018-06-30','205',' 산업은행 앞','단체','M','40대',3,842.69,7.05,30400,167
378601,'2018-06-30','211',' 여의도역 4번출구 옆','단체','M','40대',4,155.37,7.00,30180,229
378602,'2018-06-30','2337',' 대모산입구역 2번출구 앞','단체','M','40대',3,606.83,5.93,25540,181
378603,'2018-06-30','420',' 서울시 공공자전거 상암센터','단체','M','40대',2,164.66,1.15,4950,70
378604,'2018-06-30','1305',' 성북구청','단체','M','40대',2,263.55,1.82,7830,48

In [25]:
import datetime
import calendar

In [31]:
datetime.datetime.weekday(datetime.date(2018, 6, 1))

4

In [30]:
datetime.date(2018, 6, 1)

datetime.date(2018, 6, 1)

In [55]:
df['week'] = df.iloc[:,0].map(lambda x : datetime.datetime.weekday(datetime.date(int(x.split('-')[0]),int(x.split('-')[1]),int(x.split('-')[2]))))

In [37]:
int('01')

1

In [59]:
type("대여일자")

str

In [60]:
type(df.iloc[:, 1])

pandas.core.series.Series

In [49]:
df["'대여일자'"]

0         '2018-06-01'
1         '2018-06-01'
2         '2018-06-01'
3         '2018-06-01'
4         '2018-06-01'
5         '2018-06-01'
6         '2018-06-01'
7         '2018-06-01'
8         '2018-06-01'
9         '2018-06-01'
10        '2018-06-01'
11        '2018-06-01'
12        '2018-06-01'
13        '2018-06-01'
14        '2018-06-01'
15        '2018-06-01'
16        '2018-06-01'
17        '2018-06-01'
18        '2018-06-01'
19        '2018-06-01'
20        '2018-06-01'
21        '2018-06-01'
22        '2018-06-01'
23        '2018-06-01'
24        '2018-06-01'
25        '2018-06-01'
26        '2018-06-01'
27        '2018-06-01'
28        '2018-06-01'
29        '2018-06-01'
              ...
378575    '2018-06-30'
378576    '2018-06-30'
378577    '2018-06-30'
378578    '2018-06-30'
378579    '2018-06-30'
378580    '2018-06-30'
378581    '2018-06-30'
378582    '2018-06-30'
378583    '2018-06-30'
378584    '2018-06-30'
378585    '2018-06-30'
378586    '2018-06-30'
378587    '2018-06-30'
378588    '2018-06-30'
378589    '2018-06-30'
378590    '2018-06-30'
378591    '2018-06-30'
378592    '2018-06-30'
378593    '2018-06-30'
378594    '2018-06-30'
378595    '2018-06-30'
378596    '2018-06-30'
378597    '2018-06-30'
378598    '2018-06-30'
378599    '2018-06-30'
378600    '2018-06-30'
378601    '2018-06-30'
378602    '2018-06-30'
378603    '2018-06-30'
378604    '2018-06-30'
Name: '대여일자', Length: 378605, dtype: object

In [58]:
df.iloc[:,1] = df.iloc[:,1].str.replace("'","")

In [61]:
df

,'대여일자','대여소번호','대여소','대여구분코드','SEX_CD','연령대코드','이용건수','운동량','탄소량','이동거리(M)','이동시간(분)',week
0,2018-06-01,733,' 신정이펜하우스314동','정기','F','~10대',3,290.72,2.66,11490,93,4
1,2018-06-01,736,' 오솔길공원','정기','F','~10대',2,50.54,0.61,2600,18,4
2,2018-06-01,746,' 목동2단지 상가','정기','F','~10대',1,53.02,0.48,2060,51,4
3,2018-06-01,945,' 기자촌 사거리','정기','F','~10대',1,54.33,0.65,2800,17,4
4,2018-06-01,508,' 성수아카데미타워 앞','정기','F','~10대',1,46.81,0.46,1970,11,4
5,2018-06-01,1041,' 묘곡초등학교','정기','F','~10대',2,111.69,1.13,4900,23,4
6,2018-06-01,1044,' 굽은다리역','정기','F','~10대',1,33.98,0.33,1430,7,4
7,2018-06-01,1152,' 마곡역교차로','정기','F','~10대',1,12.67,0.15,640,3,4
8,2018-06-01,1153,' 발산역 2번출구','정기','F','~10대',3,67.09,0.69,2990,23,4
9,2018-06-01,1157,' 강서구청','정기','F','~10대',1,39.12,0.35,1520,12,4
10,2018-06-01,1251,' 석촌역 2번출구','정기','F','~10대',1,53.66,0.63,2710,18,4
11,2018-06-01,1262,' 송파여성문화회관 앞','정기','F','~10대',1,33.66,0.39,1700,12,4
12,2018-06-01,1265,' 문정동 근린공원','정기','F','~10대',2,222.19,2.24,9650,59,4
13,2018-06-01,1442,' (구)신한은행 중랑교지점','정기','F','~10대',1,111.20,1.00,4320,27,4
14,2018-06-01,1526,' 수유동 채선당앞','정기','F','~10대',1,9.78,0.09,380,3,4
15,2018-06-01,1530,' 광산사거리','정기','F','~10대',2,21.88,0.19,850,6,4
16,2018-06-01,1533,"' 번동 주공3, 4단지 교차로'",'정기','F','~10대',1,34.59,0.42,1820,11,4
17,2018-06-01,1643,' 태릉입구역 8번출구','정기','F','~10대',1,49.74,0.36,1570,11,4
18,2018-06-01,1653,' 노원역1번출구','정기','F','~10대',1,24.00,0.23,1010,6,4
19,2018-06-01,1715,' 서울특별시교육청도봉도서관','정기','F','~10대',1,33.77,0.38,1640,7,4
20,2018-06-01,1720,' 도봉구청 옆(중랑천변)','정기','F','~10대',1,259.46,2.17,9360,60,4
21,2018-06-01,300,' 정동사거리','정기','F','~10대',1,0.00,0.00,0,0,4
22,2018-06-01,2362,' 신사동 가로수길 입구','정기','F','~10대',1,42.21,0.38,1640,9,4
23,2018-06-01,2373,' 개포동역 사거리','정기','F','~10대',1,44.79,0.40,1740,12,4
24,2018-06-01,3511,' 응봉역 1번출구','정기','F','~10대',1,257.40,2.32,10000,59,4
25,2018-06-01,3513,' 상왕십리역 1번출구','정기','F','~10대',1,28.57,0.26,1110,4,4
26,2018-06-01,115,' 사루비아 빌딩 앞','정기','F','~10대',1,39.35,0.48,2070,35,4
27,2018-06-01,1337,' 돈암성당 옆','정기','F','~10대',2,114.35,1.28,5500,51,4
28,2018-06-01,1338,' 용문2교 옆','정기','F','~10대',1,257.40,2.32,10000,82,4
29,2018-06-01,1342,' 성북쉼터 앞','정기','F','~10대',1,36.83,0.36,1550,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...
378575,2018-06-30,1122,' 황금내근린공원','단체','M','20대',2,515.21,3.87,16680,97,5
378576,2018-06-30,1413,' 봉화산역 5번출구 뒤','단체','M','20대',1,87.77,0.93,4030,22,5
378577,2018-06-30,1911,' 구로디지털단지역 앞','단체','M','20대',2,242.22,2.19,9410,82,5
378578,2018-06-30,2027,' 중앙대학교 정문','단체','M','20대',5,3242.05,18.99,81870,861,5
378579,2018-06-30,2102,' 봉림교 교통섬','단체','M','20대',4,153.09,1.43,6120,32,5
378580,2018-06-30,2107,' 도림천 신화교','단체','M','20대',2,76.36,0.72,3110,19,5
378581,2018-06-30,1203,' 밀리아나2빌딩 앞','단체','M','20대',2,183.79,1.27,5460,28,5
378582,2018-06-30,2247,'섬들근린공원','단체','M','20대',3,343.04,2.61,11250,57,5
378583,2018-06-30,2307,' 압구정 한양 3차 아파트','단체','M','20대',5,621.93,4.86,20940,147,5
378584,2018-06-30,1430,' 중랑구청','단체','M','20대',5,201.69,2.14,9260,65,5
378585,2018-06-30,2136,' 신림역 8번출구','단체','M','20대',2,454.94,3.46,14920,109,5
378586,2018-06-30,3504,' 원일교회','단체','M','20대',2,84.20,0.87,3730,55,5
378587,2018-06-30,1251,' 석촌역 2번출구','단체','M','30대',2,135.42,0.96,4120,87,5
378588,2018-06-30,311,' 서울광장 옆','단체','M','30대',2,233.96,1.96,8440,110,5
378589,2018-06-30,914,' 새절역 2번출구','단체','M','30대',2,442.31,2.91,12550,173,5
378590,2018-06-30,2009,' 보라매역 8번출구','단체','M','30대',2,113.30,0.94,4030,25,5
378591,2018-06-30,2285,' LH서초3단지 301동 맞은편','단체','M','40대',3,521.53,5.09,21950,148,5
378592,2018-06-30,3519,' 용답역 1번 출구','단체','M','40대',1,34.67,0.24,1030,7,5
378593,2018-06-30,116,' 일진아이윌아파트 옆','단체','M','40대',2,188.18,1.22,5280,58,5
378594,2018-06-30,1278,' 송파구청 교차로','단체','M','40대',2,355.41,4.16,17950,116,5
378595,2018-06-30,1286,' 위례중앙푸르지오 1단지 앞','단체','M','40대',2,485.37,3.89,16790,109,5
378596,2018-06-30,170,' 가재울 뉴타운 주유소 옆','단체','M','40대',2,329.21,2.97,12790,95,5
378597,2018-06-30,703,' 오목교역 7번출구 앞','단체','M','40대',2,1360.73,17.72,76360,454,5
378598,2018-06-30,583,' 청계천 생태교실 앞','단체','M','40대',1,63.95,0.44,1900,10,5
378599,2018-06-30,202,' 국민일보 앞','단체','M','40대',4,64.97,2.93,12620,145,5
378600,2018-06-30,205,' 산업은행 앞','단체','M','40대',3,842.69,7.05,30400,167,5
378601,2018-06-30,211,' 여의도역 4번출구 옆','단체','M','40대',4,155.37,7.00,30180,229,5
378602,2018-06-30,2337,' 대모산입구역 2번출구 앞','단체','M','40대',3,606.83,5.93,25540,181,5
378603,2018-06-30,420,' 서울시 공공자전거 상암센터','단체','M','40대',2,164.66,1.15,4950,70,5
378604,2018-06-30,1305,' 성북구청','단체','M','40대',2,263.55,1.82,7830,48,5

In [56]:
df

,'대여일자','대여소번호','대여소','대여구분코드','SEX_CD','연령대코드','이용건수','운동량','탄소량','이동거리(M)','이동시간(분)',week
0,2018-06-01,'733',' 신정이펜하우스314동','정기','F','~10대',3,290.72,2.66,11490,93,4
1,2018-06-01,'736',' 오솔길공원','정기','F','~10대',2,50.54,0.61,2600,18,4
2,2018-06-01,'746',' 목동2단지 상가','정기','F','~10대',1,53.02,0.48,2060,51,4
3,2018-06-01,'945',' 기자촌 사거리','정기','F','~10대',1,54.33,0.65,2800,17,4
4,2018-06-01,'508',' 성수아카데미타워 앞','정기','F','~10대',1,46.81,0.46,1970,11,4
5,2018-06-01,'1041',' 묘곡초등학교','정기','F','~10대',2,111.69,1.13,4900,23,4
6,2018-06-01,'1044',' 굽은다리역','정기','F','~10대',1,33.98,0.33,1430,7,4
7,2018-06-01,'1152',' 마곡역교차로','정기','F','~10대',1,12.67,0.15,640,3,4
8,2018-06-01,'1153',' 발산역 2번출구','정기','F','~10대',3,67.09,0.69,2990,23,4
9,2018-06-01,'1157',' 강서구청','정기','F','~10대',1,39.12,0.35,1520,12,4
10,2018-06-01,'1251',' 석촌역 2번출구','정기','F','~10대',1,53.66,0.63,2710,18,4
11,2018-06-01,'1262',' 송파여성문화회관 앞','정기','F','~10대',1,33.66,0.39,1700,12,4
12,2018-06-01,'1265',' 문정동 근린공원','정기','F','~10대',2,222.19,2.24,9650,59,4
13,2018-06-01,'1442',' (구)신한은행 중랑교지점','정기','F','~10대',1,111.20,1.00,4320,27,4
14,2018-06-01,'1526',' 수유동 채선당앞','정기','F','~10대',1,9.78,0.09,380,3,4
15,2018-06-01,'1530',' 광산사거리','정기','F','~10대',2,21.88,0.19,850,6,4
16,2018-06-01,'1533',"' 번동 주공3, 4단지 교차로'",'정기','F','~10대',1,34.59,0.42,1820,11,4
17,2018-06-01,'1643',' 태릉입구역 8번출구','정기','F','~10대',1,49.74,0.36,1570,11,4
18,2018-06-01,'1653',' 노원역1번출구','정기','F','~10대',1,24.00,0.23,1010,6,4
19,2018-06-01,'1715',' 서울특별시교육청도봉도서관','정기','F','~10대',1,33.77,0.38,1640,7,4
20,2018-06-01,'1720',' 도봉구청 옆(중랑천변)','정기','F','~10대',1,259.46,2.17,9360,60,4
21,2018-06-01,'300',' 정동사거리','정기','F','~10대',1,0.00,0.00,0,0,4
22,2018-06-01,'2362',' 신사동 가로수길 입구','정기','F','~10대',1,42.21,0.38,1640,9,4
23,2018-06-01,'2373',' 개포동역 사거리','정기','F','~10대',1,44.79,0.40,1740,12,4
24,2018-06-01,'3511',' 응봉역 1번출구','정기','F','~10대',1,257.40,2.32,10000,59,4
25,2018-06-01,'3513',' 상왕십리역 1번출구','정기','F','~10대',1,28.57,0.26,1110,4,4
26,2018-06-01,'115',' 사루비아 빌딩 앞','정기','F','~10대',1,39.35,0.48,2070,35,4
27,2018-06-01,'1337',' 돈암성당 옆','정기','F','~10대',2,114.35,1.28,5500,51,4
28,2018-06-01,'1338',' 용문2교 옆','정기','F','~10대',1,257.40,2.32,10000,82,4
29,2018-06-01,'1342',' 성북쉼터 앞','정기','F','~10대',1,36.83,0.36,1550,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...
378575,2018-06-30,'1122',' 황금내근린공원','단체','M','20대',2,515.21,3.87,16680,97,5
378576,2018-06-30,'1413',' 봉화산역 5번출구 뒤','단체','M','20대',1,87.77,0.93,4030,22,5
378577,2018-06-30,'1911',' 구로디지털단지역 앞','단체','M','20대',2,242.22,2.19,9410,82,5
378578,2018-06-30,'2027',' 중앙대학교 정문','단체','M','20대',5,3242.05,18.99,81870,861,5
378579,2018-06-30,'2102',' 봉림교 교통섬','단체','M','20대',4,153.09,1.43,6120,32,5
378580,2018-06-30,'2107',' 도림천 신화교','단체','M','20대',2,76.36,0.72,3110,19,5
378581,2018-06-30,'1203',' 밀리아나2빌딩 앞','단체','M','20대',2,183.79,1.27,5460,28,5
378582,2018-06-30,'2247','섬들근린공원','단체','M','20대',3,343.04,2.61,11250,57,5
378583,2018-06-30,'2307',' 압구정 한양 3차 아파트','단체','M','20대',5,621.93,4.86,20940,147,5
378584,2018-06-30,'1430',' 중랑구청','단체','M','20대',5,201.69,2.14,9260,65,5
378585,2018-06-30,'2136',' 신림역 8번출구','단체','M','20대',2,454.94,3.46,14920,109,5
378586,2018-06-30,'3504',' 원일교회','단체','M','20대',2,84.20,0.87,3730,55,5
378587,2018-06-30,'1251',' 석촌역 2번출구','단체','M','30대',2,135.42,0.96,4120,87,5
378588,2018-06-30,'311',' 서울광장 옆','단체','M','30대',2,233.96,1.96,8440,110,5
378589,2018-06-30,'914',' 새절역 2번출구','단체','M','30대',2,442.31,2.91,12550,173,5
378590,2018-06-30,'2009',' 보라매역 8번출구','단체','M','30대',2,113.30,0.94,4030,25,5
378591,2018-06-30,'2285',' LH서초3단지 301동 맞은편','단체','M','40대',3,521.53,5.09,21950,148,5
378592,2018-06-30,'3519',' 용답역 1번 출구','단체','M','40대',1,34.67,0.24,1030,7,5
378593,2018-06-30,'116',' 일진아이윌아파트 옆','단체','M','40대',2,188.18,1.22,5280,58,5
378594,2018-06-30,'1278',' 송파구청 교차로','단체','M','40대',2,355.41,4.16,17950,116,5
378595,2018-06-30,'1286',' 위례중앙푸르지오 1단지 앞','단체','M','40대',2,485.37,3.89,16790,109,5
378596,2018-06-30,'170',' 가재울 뉴타운 주유소 옆','단체','M','40대',2,329.21,2.97,12790,95,5
378597,2018-06-30,'703',' 오목교역 7번출구 앞','단체','M','40대',2,1360.73,17.72,76360,454,5
378598,2018-06-30,'583',' 청계천 생태교실 앞','단체','M','40대',1,63.95,0.44,1900,10,5
378599,2018-06-30,'202',' 국민일보 앞','단체','M','40대',4,64.97,2.93,12620,145,5
378600,2018-06-30,'205',' 산업은행 앞','단체','M','40대',3,842.69,7.05,30400,167,5
378601,2018-06-30,'211',' 여의도역 4번출구 옆','단체','M','40대',4,155.37,7.00,30180,229,5
378602,2018-06-30,'2337',' 대모산입구역 2번출구 앞','단체','M','40대',3,606.83,5.93,25540,181,5
378603,2018-06-30,'420',' 서울시 공공자전거 상암센터','단체','M','40대',2,164.66,1.15,4950,70,5
378604,2018-06-30,'1305',' 성북구청','단체','M','40대',2,263.55,1.82,7830,48,5